apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-ui-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway   # 🔥 MUST ADD
spec:
  ingressClassName: azure-application-gateway
  rules:
  - host: ui.sohitguptadevops.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: todo-ui
            port:
              number: 80
